# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OgTeam1PA1

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HealthMessageTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HealthMessageTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealthMessageTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HealthMessageTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HealthMessageTable
    def Dispenser(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthMessageTable
    def Icemaker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthMessageTable
    def Lightbulb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthMessageTable
    def FridgeTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthMessageTable
    def FreezerTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthMessageTable
    def SensorStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthMessageTable
    def DoorStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def HealthMessageTableStart(builder):
    builder.StartObject(7)

def Start(builder):
    HealthMessageTableStart(builder)

def HealthMessageTableAddDispenser(builder, dispenser):
    builder.PrependInt32Slot(0, dispenser, 0)

def AddDispenser(builder, dispenser):
    HealthMessageTableAddDispenser(builder, dispenser)

def HealthMessageTableAddIcemaker(builder, icemaker):
    builder.PrependInt32Slot(1, icemaker, 0)

def AddIcemaker(builder, icemaker):
    HealthMessageTableAddIcemaker(builder, icemaker)

def HealthMessageTableAddLightbulb(builder, lightbulb):
    builder.PrependInt32Slot(2, lightbulb, 0)

def AddLightbulb(builder, lightbulb):
    HealthMessageTableAddLightbulb(builder, lightbulb)

def HealthMessageTableAddFridgeTemp(builder, fridgeTemp):
    builder.PrependInt32Slot(3, fridgeTemp, 0)

def AddFridgeTemp(builder, fridgeTemp):
    HealthMessageTableAddFridgeTemp(builder, fridgeTemp)

def HealthMessageTableAddFreezerTemp(builder, freezerTemp):
    builder.PrependInt32Slot(4, freezerTemp, 0)

def AddFreezerTemp(builder, freezerTemp):
    HealthMessageTableAddFreezerTemp(builder, freezerTemp)

def HealthMessageTableAddSensorStatus(builder, sensorStatus):
    builder.PrependInt32Slot(5, sensorStatus, 0)

def AddSensorStatus(builder, sensorStatus):
    HealthMessageTableAddSensorStatus(builder, sensorStatus)

def HealthMessageTableAddDoorStatus(builder, doorStatus):
    builder.PrependInt32Slot(6, doorStatus, 0)

def AddDoorStatus(builder, doorStatus):
    HealthMessageTableAddDoorStatus(builder, doorStatus)

def HealthMessageTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return HealthMessageTableEnd(builder)
