# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OgTeam1PA1

class MilkType(object):
    onePercent = 0
    twoPercent = 1
    fatFree = 2
    whole = 3
    almond = 4
    cashew = 5
    oat = 6
