# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OgTeam1PA1

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResponseMessageTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResponseMessageTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponseMessageTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResponseMessageTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResponseMessageTable
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ResponseMessageTable
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ResponseMessageTableStart(builder):
    builder.StartObject(2)

def Start(builder):
    ResponseMessageTableStart(builder)

def ResponseMessageTableAddCode(builder, code):
    builder.PrependInt32Slot(0, code, 0)

def AddCode(builder, code):
    ResponseMessageTableAddCode(builder, code)

def ResponseMessageTableAddContents(builder, contents):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)

def AddContents(builder, contents):
    ResponseMessageTableAddContents(builder, contents)

def ResponseMessageTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ResponseMessageTableEnd(builder)
